/* THIS CODE IS AUTOMATICALLY GENERATED BY COMPILECOUNT. */
#pragma once
#ifndef WILDCAT_COMPILE_COUNT_HPP
#define WILDCAT_COMPILE_COUNT_HPP

/* CompileCount.hpp
	CompileCount
	This program dynamically generates a header file with a string which counts compilations. This can help with versioning. In future we might also store compilation date and time, although G++ already has this feature with __TIME__ and __DATE__.
*/
	#include <string>

	const std::string COMPILE_COUNT = "4400";
#endif
